/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.salvacomes.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RegistryUsers service. Represents a row in the &quot;RegistryForm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>org.salvacomes.model.impl.RegistryUsersModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>org.salvacomes.model.impl.RegistryUsersImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistryUsers
 * @generated
 */
@ProviderType
public interface RegistryUsersModel extends BaseModel<RegistryUsers> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registry users model instance should use the {@link RegistryUsers} interface instead.
	 */

	/**
	 * Returns the primary key of this registry users.
	 *
	 * @return the primary key of this registry users
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this registry users.
	 *
	 * @param primaryKey the primary key of this registry users
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this registry users.
	 *
	 * @return the ID of this registry users
	 */
	public int getId();

	/**
	 * Sets the ID of this registry users.
	 *
	 * @param id the ID of this registry users
	 */
	public void setId(int id);

	/**
	 * Returns the name of this registry users.
	 *
	 * @return the name of this registry users
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this registry users.
	 *
	 * @param name the name of this registry users
	 */
	public void setName(String name);

	/**
	 * Returns the last name of this registry users.
	 *
	 * @return the last name of this registry users
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this registry users.
	 *
	 * @param lastName the last name of this registry users
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the birthday of this registry users.
	 *
	 * @return the birthday of this registry users
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this registry users.
	 *
	 * @param birthday the birthday of this registry users
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the email of this registry users.
	 *
	 * @return the email of this registry users
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this registry users.
	 *
	 * @param email the email of this registry users
	 */
	public void setEmail(String email);

	/**
	 * Returns the registry date of this registry users.
	 *
	 * @return the registry date of this registry users
	 */
	public Date getRegistryDate();

	/**
	 * Sets the registry date of this registry users.
	 *
	 * @param registryDate the registry date of this registry users
	 */
	public void setRegistryDate(Date registryDate);

}